### ISSUE TITLE
Moment deprecated warnings

### ISSUE THREAD

**Issue by johngeorgewright** [mx4492/hubot-remind-her#2]
```
hubot> hubot remind me in 1 minute to do something
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. https://github.com/moment/moment/issues/1779
Error:
  at deprecate node_modules/hubot-remind-her/node_modules/moment/moment.js:738:42)
  at node_modules/hubot-remind-her/node_modules/moment/moment.js:2554:37
  at hookCallback (node_modules/hubot-remind-her/node_modules/moment/moment.js:8:85)
  at Object.<anonymous> (node_modules/hubot-remind-her/node_modules/moment/moment.js:11:2)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (node_modules/hubot-remind-her/node_modules/chrono-node/src/parsers/EN/ENISOFormatParser.js:10:14)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (node_modules/hubot-remind-her/node_modules/chrono-node/src/options.js:1:87)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (node_modules/hubot-remind-her/node_modules/chrono-node/src/chrono.js:2:33)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (node_modules/hubot-remind-her/scripts/remind-her.coffee:13:10, <js>:5:12)
  at Object.<anonymous> (node_modules/hubot-remind-her/scripts/remind-her.coffee:13:1, <js>:113:4)
  at Module._compile (module.js:456:26)
  at Object.loadFile (node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Robot.loadFile (node_modules/hubot/src/robot.coffee:217:9, <js>:164:20)
  at Robot.load (node_modules/hubot/src/robot.coffee:239:9, <js>:187:30)
  at module.exports (node_modules/hubot-remind-her/index.coffee:5:3, <js>:9:18)
  at Robot.loadExternalScripts (node_modules/hubot/src/robot.coffee:263:11, <js>:212:39)
  at node_modules/hubot/bin/hubot:119:11, <js>:123:26
  at fs.js:272:14
  at Object.oncomplete (fs.js:108:15)
```

**Comment by johngeorgewright** [comment]
Just realised this is probably do to with chrono-node.
